import random

def quote(l):
  n = len(l) -1
  random_number = random.randint(0, n)
  print(l[random_number])
  

list = ["No guts, no story. -Chris Brady",
"My life is my message.- Mahatma Gandhi",
"Screw it, let’s do it. -Richard Branson",
"Boldness be my friend. -William Shakespeare",
"Keep going. Be all in.- Bryan Hutchinson",
"My life is my argument.- Albert Schweitzer",
"Leave no stone unturned.- Euripides",
"Fight till the last gasp. -William Shakespeare",
"Stay hungry. Stay foolish. –Steve Jobs ",
"You can if you think you can. -George Reeves",
"Whatever you are, be a good one. -Abraham Lincoln",
"Impossible is for the unwilling. -John Keats",
"The wisest mind has something yet to learn. –George Santanaya",
"The past does not equal the future. -Tony Robbins",
"Good things happen to those who hustle. -Anaïs Nin",
"If it matters to you, you’ll find a way. -Charlie Gilkey",
"Forget about style; worry about results. Bobby Orr",
"Whatever you do, do with all your might.- Marcus Tullius Cicero",
"Every noble work is at first impossible. -Thomas Carlyle",
"If you’re going through hell, keep going. -Winston Churchill",
"We are twice armed if we fight with faith. -Plato",
"Be faithful to that which exists within yourself. -André Gide",
"Persistence guarantees that results are inevitable.- Paramahansa Yogananda",
"In life you need either inspiration or desperation. -Tony Robbins",
"I would rather die on my feet than live on my knees. -Euripides",
"The true success is the person who invented himself. -Al Goldstein",
"Let him that would move the world first move himself. -Socrates",
"Go forth on your path, as it exists only through your walking. -Augustine of Hippo",
"We can do anything we want to if we stick to it long enough.- Helen Keller",
"It does not matter how slowly you go as long as you do not stop. -Confucius",
"Life is fragile. We’re not guaranteed a tomorrow so give it everything you’ve got. -Tim Cook",
"The two most important days in your life are the day you are born and they day you find out why. -Mark Twain",
"Each day provides its own gifts. –Marcus Aurelius",
"Try Again. Fail again. Fail better. – Samuel Beckett",
"Nothing is worth more than this day. -Johann Wolfgang von Goethe",
"Focus on the journey, not the destination. -Greg Anderson",
"Believe you can and you’re halfway there. -Theodore Roosevelt",
"Once you choose hope, anything’s possible. -Christopher Reeve",
"The first step is you have to say that you can. -Will Smith",
"Start every day off with a smile and get it over with. -W. C. Fields",
"If you want to lift yourself up, lift up someone else. -Booker T. Washington",
"Don’t go through life, grow through life. -Eric Butterworth",
"A problem is a chance for you to do your best. -Duke Ellington",
"You are amazing. As you are. Stronger than you know. More beautiful than you think. –Tia Sparkles",
"If you are not too long, I will wait here for you all my life. -Oscar Wilde",
"To the world you may be one person, but to one person you are the world. -Bill Wilson",
"I love you not only for what you are, but for what I am when I am with you. -Ray Croft",
"You have to be odd to be number one. -Dr. Seuss ",
"Please all, and you will please none. -Aesop",
"The fool wonders, the wise man asks. -Benjamin Disraeli",
"A man can’t ride your back unless it’s bent. -Martin Luther King Jr.",
"Chop your own wood and it will warm you twice. -Henry Ford",
"Some people are so poor, all they have is money. -Jack Kerouac",
"All generalizations are false, including this one. -Mark Twain",
"It’s not what you look at that matters, it’s what you see. -Henry David Thoreau",
"There is no saint without a past, no sinner without a future. -Augustine of Hippo ",
"We make a living by what we get, but we make a life by what we give. -Winston Churchill",
"It’s no wonder that truth is stranger than fiction. Fiction has to make sense. -Mark Twain",
"The man who wants to lead the orchestra must turn his back on the crowd. -James Crook",
"What counts can’t always be counted; what can be counted doesn’t always count. –Albert Einstein",
"As a well-spent day brings happy sleep, so a life well spent brings happy death. -Leonardo da Vinci",
"Life is not about how fast you run or how high you climb, but how well you bounce. -Vivian Komori",
"Concentration is the ability to think about absolutely nothing when it is absolutely necessary. -Ray Knight",
"It is better to remain silent and be thought a fool than to open one’s mouth and remove all doubt. -Mark Twain",
"Seek the seeker. -Ramana Maharshi",
"No pressure, no diamonds. -Thomas Carlyle",
"Every wall is a door. -Ralph Waldo Emerson",
"The only truth is music. -Jack Kerouac",
"Stay foolish to stay sane. -Maxime Lagacé",
"If youth knew; if age could. -Sigmund Freud",
"Time is the soul of this world. -Pythagoras",
"He not busy being born is busy dying. -Bob Dylan",
"It takes a long time to become young. -Pablo Picasso",
"Innocence is courage and clarity both. -Osho",
"Find what you love and let it kill you. Charles Bukowski",
"Sadness flies away on the wings of time. -Jean de La Fontaine",
"I am not young enough to know everything. -Oscar Wilde",
"It is not length of life, but depth of life. -Ralph Waldo Emerson",
"Life is like the ocean, it goes up and down. -Vanessa Paradis",
"You’ve gotta know what death is to know life. -Jack Kevorkian",
"Don’t let yesterday take up too much of today. -Will Rogers",
"Solitary trees, if they grow at all, grow strong. -Winston Churchill",
"The bird a nest, the spider a web, man friendship. -William Blake",
"Life is a question and how we live it is our answer. -Gary Keller",
"God provides the wind, but man must raise the sails. -Augustine of Hippo",
"Art is the lie that enables us to realize the truth. -Pablo Picasso",
"The truth isn’t always beauty, but the hunger for it is. -Nadine Gordimer",
"Life without love is like a tree without blossoms or fruit. -Khalil Gibran",
"The knowledge of happiness brings the knowledge of unhappiness. -Swami Vivekananda",
"There are those who give with joy, and that joy is their reward. -Khalil Gibran",
"Life is the car, your heart is the key and God is the chauffeur. -Sri Sathya Sai Baba",
"You are not a drop in the ocean. You are the entire ocean in a drop. -Rumi",
"One is never afraid of the unknown; one is afraid of the known coming to an end. -Jiddu Krishnamurti",
"When you’ve seen beyond yourself, then you may find, peace of mind is waiting there. -George Harrison",
"So it goes. -Kurt Vonnegut ",
"Live the life you’ve dreamed. -Henry David Thoreau",
"Life is not fair; get used to it. -Bill Gates",
"Life is a long lesson in humility. -James M. Barrie",
"Life is a lively process of becoming. -Douglas MacArthur",
"Life is largely a matter of expectation. -Homer",
"Anything worth doing is worth doing slowly. -Mae West",
"Life is too important to be taken seriously. -Oscar Wilde",
"Life is either a daring adventure or nothing. -Helen Keller",
"The sole meaning of life is to serve humanity. -Leo Tolstoy",
"Love the life you live. Lead the life you love. -Bob Marley",
"Life is accepting what is and working from that. -Gloria Naylor",
"We are all, right now, living the life we choose. -Peter McWilliams",
"Not life, but good life, is to be chiefly valued. -Socrates",
"Live your life, do your work, then take your hat. -Henry David Thoreau ",
"Life got to be about more than just solving problems. -Elon Musk",
"Life isn’t as serious as the mind makes it out to be. -Eckhart Tolle",
"Life is about making an impact, not making an income. -Kevin Kruse",
"The quality of life is more important than life itself. -Alexis Carrel",
"You have to die a few times before you can really live. -Charles Bukowski",
"What’s coming will come and we’ll meet it when it does. -Hagrid",
"Life shrinks or expands in proportion to one’s courage. -Anaïs Nin",
"Life is defined more by its risks than by its samenesses. -Mary Anne Radmacher",
"You only live once, but if you do it right, once is enough. -Mae West",
"Sometimes life has its way with you when you least expect it. -Jon Hamm",
"Life isn’t about getting and having, it’s about giving and being. -Kevin Kruse",
"Life is amazing. Life is fucking messy. Life is what you make of it. -Dwayne Johnson",
"Life is not a problem to be solved, but a reality to be experienced. -Soren Kierkegaard",
"Nowadays people know the price of everything and the value of nothing. -Oscar Wilde",
"Don’t be afraid your life will end. Be afraid that it will never begin. -Grace Hansen",
"To live is the rarest thing in the world. Most people exist, that is all. -Oscar Wilde",
"To love is to act. -Victor Hugo ",
"All you need is love.- John Lennon",
"Do all things with love.- Og Mandino",
"Every lover is a soldier. -Ovid",
"Who, being loved, is poor? -Oscar Wilde",
"Speak low, if you speak love. -William Shakespeare",
"Love is the absence of judgment. -Dalai Lama",
"If you wished to be loved, love. -Lucius Annaeus Seneca",
"Love the sinner and hate the sin. -Augustine of Hippo",
"If a thing loves, it is infinite. -William Blake",
"In true love, you attain freedom. -Thich Nhat Hanh",
"Economized love is never real love. -Honore De Balzac",
"Love does not dominate; it cultivates. -Johann Wolfgang von Goethe",
"The more you judge, the less you love. -Honore de Balzac",
"Lovers quarrels are the renewal of love. -Terence",
"Life is a game and true love is a trophy. -Rufus Wainwright",
"To love is to receive a glimpse of heaven. -Karen Sunde",
"Love is the flower you’ve got to let grow. -John Lennon",
"If love appears, boundaries will disappear. -Osho",
"Intense love does not measure, it just gives. -Mother Teresa",
"They do not love that do not show their love. -William Shakespeare",
"Absence sharpens love, presence strengthens it. -Benjamin Franklin",
"The more you love, the more you become lovable. -Osho",
"You cannot save people, you can just love them.- Anaïs Nin",
"Love is a thing that is full of cares and fears.- Ovid",
"It is love alone that gives worth to all things. -Teresa of Avila",
"Life in abundance comes only through great love.- Elbert Hubbard",
"Love does not claim possession, but gives freedom. -Rabindranath Tagore",
"The art of love is largely the art of persistence. -Albert Ellis",
"If you judge people, you have no time to love them. -Mother Teresa",
"Never love anyone who treats you like you’re ordinary. -Oscar Wilde",
"Follow love and it will flee, flee love and it will follow. -John Gay",
"Love is like the wind, you can’t see it but you can feel it. -Nicholas Sparks",
"Perhaps one did not want to be loved so much as to be understood.- George Orwell",
"Where’s your will to be weird? -Jim Morrison ",
"Above all things, reverence yourself.- Pythagoras",
"Self-respect knows no considerations. -Mohandas Gandhi",
"No one is laughable who laughs at himself. -Lucius Annaeus Seneca",
"Why fit in when you were born to stand out? -Dr. Seuss",
"Personal love is concentrated universal love.- Maharishi Mahesh Yogi",
"We must be our own before we can be another’s. -Ralph Waldo Emerson",
"Accept who you are. Unless you’re a serial killer. -Ellen DeGeneres",
"Beauty begins the moment you decide to be yourself. -Coco Chanel",
"Wanting to be someone else is a waste of who you are. -Kurt Cobain",
"To love oneself is the beginning of a lifelong romance. -Oscar Wilde",
"If you are lonely when you’re alone, you are in bad company. -Jean-Paul Sartre",
"The worst loneliness is not to be comfortable with yourself.- Mark Twain",
"The reward for conformity is that everyone likes you but yourself. -Rita Mae Brown",
"Freedom lies in being bold. -Robert Frost",
"A happy wife is a happy life. -Gavin Rossdale",
"Boredom: the desire for desires. -Leo Tolstoy",
"Happiness depends upon us. -Aristotle",
"The less I needed, the better I felt. -Charles Bukowski",
"Be happy in the moment, that’s enough. -Mother Teresa",
"Happiness can exist only in acceptance. -George Orwell",
"Man is the artificer of his own happiness. -Henry David Thoreau",
"One of the keys to happiness is a bad memory. -Rita Mae Brown",
"To live happily is an inward power of the soul. -Marcus Aurelius",
"Anything you’re good at contributes to happiness. Bertrand Russell",
"A happy soul is the best shield for a cruel world. -Atticus",
"There is no way to happiness. Happiness is the way. -Thich Nhat Hanh",
"The best way to pay for a lovely moment is to enjoy it. -Richard Bach",
"If you carry joy in your heart, you can heal any moment. -Carlos Santana",
"Life’s greatest happiness is to be convinced we are loved. -Victor Hugo",
"Be happy with what you have. Be excited about what you want. Alan Cohen",
"Find ecstasy in life; the mere sense of living is joy enough.- Emily Dickinson",
"To be content means that you realize you contain what you seek. -Alan Cohen",
"Happy are those who dare courageously to defend what they love. -Ovid",
"Doing what you like is freedom. Liking what you do is happiness. -Frank Tyger",
"The key to happiness is doing something you like every single day. –Victor Pride",
"We don’t laugh because we’re happy – we’re happy because we laugh. -William James",
"A friend is a second self. -Aristotle",
"Choose people who lift you up. -Michelle Obama",
"Love is blind; friendship closes its eyes. -Friedrich Nietzsche",
"The greatest gift is a portion of thyself. -Ralph Waldo Emerson",
"The only way to have a friend is to be one. -Ralph Waldo Emerson",
"Friends are the siblings God never gave us. -Mencius",
"Rare as is true love, true friendship is rarer. -Jean de La Fontaine",
"The good man is the friend of all living things. -Mahatma Gandhi",
"One loyal friend is worth ten thousand relatives. -Euripides",
"Treasure your relationships, not your possessions. -Anthony J. D’Angelo ",
"Friendship always benefits; love sometimes injures.- Seneca",
"The language of friendship is not words but meanings. -Henry David Thoreau",
"Friends? You don’t need more than your few close ones. -Alden Tan",
"Wherever we are, it is our friends that make our world. -Henry Drummond",
"My best friend is the one who brings out the best in me. -Henry Ford",
"If you have one true friend you have more than your share. -Thomas Fuller",
"The real business of life is trying to understand each other. -Gilbert Parker",
"People are lonely because they build walls instead of bridges. -Joseph F. Newton",
"Friends show their love in times of trouble, not in happiness. -Euripides",
"A friend is someone who knows all about you and still loves you.- Elbert Hubbard",
"The greatest gift of life is friendship, and I have received it. -Hubert H. Humphrey",
"Count your blessings. -Og Mandino",
"Gratitude is the sign of noble souls. -Aesop",
"Joy is the simplest form of gratitude. -Karl Barth",
"Gratitude is riches. Complaint is poverty. -Doris Day",
"Silent gratitude isn’t very much to anyone. -Gertrude Stein",
"When one has a grateful heart, life is so beautiful. -Roy T. Bennett",
"Don’t cry because it’s over, smile because it happened. -Dr. Seuss",
"Gratitude is the fairest blossom which springs from the soul. -Henry Ward Beecher",
"The essence of all beautiful art, all great art, is gratitude. -Friedrich Nietzsche",
"Kindness is wisdom. -Philip James Bailey.",
"Fair and softly goes far. -Miguel de Cervantes.",
"Be gentle first with yourself. -Lama Yeshe",
"Do small things with great love. -Mother Teresa.",
"For it is in giving that we receive. -Francis of Assisi",
"No one has ever become poor by giving. -Anne Frank.",
"The more sympathy you give, the less you need. -Malcolm S. Forbes",
"Be kind, for everyone you meet is fighting a hard battle -Ian Maclaren",
"Be kind whenever possible. It is always possible. -Dalai Lama",
"Kindness, I’ve discovered, is everything in life. -Isaac Bashevis",
"A warm smile is the universal language of kindness.- William Arthur Ward",
"My religion is very simple. My religion is kindness.- Dalai Lama",
"We are all different. Don’t judge, understand instead. -Roy T. Bennett",
"If you can’t feed a hundred people, then feed just one.- Mother Teresa",
"What wisdom can you find that is greater than kindness? -Jean-Jacques Rousseau",
"No act of kindness, no matter how small, is ever wasted. -Aesop",
"You can accomplish by kindness what you cannot by force. -Publilius Syrus",
"The end result of kindness is that it draws people to you. -Anita Roddick",
"Kindness is like snow – it beautifies everything it covers. -Khalil Gibran",
"We shall never know all the good that a simple smile can do. -Mother Teresa",
"I don’t worry about people misinterpreting my kindness for weakness. -Jason Bateman",
"You are your choices. -Lucius Annaeus Seneca",
"My forte is awkwardness. -Zach Galifianakis",
"We are what we believe we are. -C.S. Lewis",
"The ultimate mystery is one’s own self. -Sammy Davis Jr.",
"Character is simply habit long continued. -Plutarch",
"This above all: to thine own self be true. -William Shakespeare",
"Adventure is not outside man; it is within. -George Eliot",
"You are who you are when nobody’s watching. -Stephen Fry",
"To know oneself, one should assert oneself. -Albert Camus",
"The things that we love tell us what we are. -Thomas Aquinas",
"When I am silent, I have thunder hidden inside. –Rumi",
"I may be no better, but at least I am different. -Jean-Jacques Rousseau",
"I am not the perishable body, but the eternal Self. -Ramana Maharshi",
"What I’m looking for is not out there, it is in me. -Helen Keller",
"Being entirely honest with oneself is a good exercise. -Sigmund Freud",
"As long as you can find yourself, you’ll never starve. -Suzanne Collins",
"Self-esteem is the reputation we acquire with ourselves. -Nathaniel Branden",
"Knowing others is wisdom, knowing yourself is enlightenment.- Lao Tzu",
"The only tyrant I accept in this world is the still voice within. -Mohandas Gandhi ",
"Getting in touch with your true self must be your first priority. -Tom Hopkins",
"Life isn’t about finding yourself. Life is about creating yourself. -George Bernard Shaw",
"Never be an imitator, be always original. Don’t become a carbon copy. -Osho",
"Everything you can imagine is real. -Pablo Picasso",
"Nothing happens unless first we dream. -Carl Sandburg",
"The dreamers are the saviors of the world.- James Allen ",
"If you give up on your dreams, what’s left? -Jim Carrey",
"It may be that those who do most, dream most. -Stephen Butler Leacock",
"Trust in dreams, for in them is hidden the gate to eternity.- Khalil Gibran",
"I dream. Sometimes I think that’s the only right thing to do. -Haruki Murakami",
"Dreams are often most profound when they seem the most crazy. -Sigmund Freud",
"The biggest adventure you can take is to live the life of your dreams. -Oprah Winfrey",
"The future belongs to those who believe in the beauty of their dreams. -Eleanor Roosevelt",
"To love beauty is to see light. -Victor Hugo",
"Beauty awakens the soul to act. -Dante Alighieri",
"Beauty is the promise of happiness. -Stendhal",
"Do something wonderful, people may imitate it. -Albert Schweitzer ",
"Everything has beauty, but not everyone sees it. -Confucius",
"Beauty always promises, but never gives anything. -Simone Weil",
"The human soul needs actual beauty more than bread. -D. H. Lawrence",
"Beauty begins the moment you decide to be yourself.- Coco Chanel",
"If the path be beautiful, let us not ask where it leads. -Anatole France",
"Beauty is not in the face; beauty is a light in the heart.- Khalil Gibran",
"Think of all the beauty still left around you and be happy. -Anne Frank",
"For me the greatest beauty always lies in the greatest clarity. -Gotthold Ephraim Lessing",
"The truth is not always beautiful, nor beautiful words the truth. -Lao Tzu",
"I don’t think of all the misery, but of the beauty that still remains. -Anne Frank",
"Time is money.- Benjamin Franklin",
"Time eases all things.-Sophocles",
"Lost time is never found again. -Benjamin Franklin",
"Time brings all things to pass. -Aeschylus",
"Time is the wisest counsellor of all. -Pericles",
"Time is but the stream I go fishing in. -Henry David Thoreau",
"The trouble is, you think you have time. -Jack Kornfield",
"Nothing is so dear and precious as time. -French proverb",
"Time is a game played beautifully by children.- Heraclitus",
"Don’t wait. The time will never be just right. -Mark Twain",
"Time is what we want most, but what we use worst. -William Penn",
"The two most powerful warriors are patience and time. -Leo Tolstoy ",
"In seed time learn, in harvest teach, in winter enjoy.- William Blake",
"Taking crazy things seriously is a serious waste of time. -Haruki Murakami",
"Being rich is having money, being wealthy is having time. -Stephen Swid",
"Be patient and tough; one day this pain will be useful to you. -Ovid",
"Your time is limited, so don’t waste it living someone else’s life. -Steve Jobs",
"If you love life, don’t waste time for time is what life is made up of. -Bruce Lee.",
"Simplify, simplify.- Henry David Thoreau",
"Order brings peace. -St-Augustine",
"Buy less, choose well.- Vivienne Westwood",
"Do more of what matters. –Anthony Ongaro",
"Brevity is the soul of wit. -William Shakespeare",
"Simplicity is the soul of efficiency. -Austin Freeman",
"I make myself rich by making my wants few. -Henry David Thoreau",
"Owning less is better than organizing more. J-oshua Becker",
"He is richest who is content with the least. -Socrates",
"Who is rich? He that rejoices in his portion. -Benjamin Franklin",
"Owning less is great, wanting less is better. -Joshua Becker .",
"The most important things in life aren’t things.- Anthony J. D’Angelo",
"A place for everything, everything in its place. Benjamin Franklin",
"There is more to life than increasing its speed. -Mahatma Gandhi",
"It is quality rather than quantity that matters.- Lucius Annaeus Seneca",
"The need for less often result in a life of more. –Brian Gardner",
".Owning things has a cost, and money is the least of it. –David Cain",
"Life is really simple, but we insist on making it complicated. -Confucius",
"My goal is no longer to get more done, but rather to have less to do. -Francine Jay",
"Getting all of that stuff out of your life (and your mind) is addictive. –Tynan",
"It’s not the daily increase but daily decrease. Hack away at the unessential. -Bruce Lee",
"Peace is every step. Thich Nhat Hahn",
"My aim in life is not to judge. -Jeanne Moreau",
"A smile is the beginning of peace. -Mother Teresa",
"Nonviolence is a weapon of the strong. -Mohandas Gandhi",
"Peace is the only battle worth waging. -Albert Camus",
"Nobody can bring you peace but yourself. -Ralph Waldo Emerson",
"Freedom from desire leads to inner peace. -Lao Tsu",
"It is possible to choose peace over worry.",
"There is no way to peace, peace is the way.-A.J. Muste",
"Peace is costly but it is worth the expense. -African proverb",
"Forgive, son; men are men; they needs must err. -Euripides",
"Peace comes from within. Do not seek it without. -Buddha",
"Let nothing and no one disturb your inner peace.- Luminita Saviuc",
"Peace and justice are two sides of the same coin. -Dwight D. Eisenhower",
"Peace of mind comes from not wanting to change others. -Gerald Jampolsky",
"Don’t hurry. Don’t worry. Do your best and let it rest.",
"To the mind that is still, the whole universe surrenders. -Lao Tzu",
"I know but one freedom and that is the freedom of the mind. -Antoine de Saint-Exupery",
"Let loose of what you can’t control. Serenity will be yours.",
"Time discovers truth.- Lucius Annaeus Seneca",
"Truth is a pathless land.- Jiddu Krishnamurti",
"Seek truth and you will find a path. -Frank Slaughter",
"Adversity is the first path to truth.- Lord Byron",
"Falsehood is easy, truth so difficult.- George Eliot",
"Truth is on the side of the oppressed. -Malcolm X",
"The object of the superior man is truth. -Confucius",
"The truth is rarely pure and never simple.- Oscar Wilde",
"Be truthful, nature only sides with truth. -Adolf Loos",
"There is no truth. There is only perception.- Gustave Flaubert",
"We have art in order not to die of the truth.- Friedrich Nietzsche",
"Man is the only creature that refuses to be what he is. -Albert Camus",
"Rather than love, than money, than fame, give me truth. -Henry David Thoreau",
"We search something permanent, something that will last. -Jiddu Krishnamurti",
"Seek not greatness, but seek truth and you will find both. -Horace Mann",
"To believe in something, and not to live it, is dishonest. –Mohandas Gandhi",
"If you tell the truth, you don’t have to remember anything. -Mark Twain",
"In a time of deceit telling the truth is a revolutionary act. -George Orwell",
"The truth is not for all men, but only for those who seek it. -Ayn Rand",
"The truth will set you free, but first it will make you miserable. -James A. Garfield",
"Know thyself. Socrates",
"Wisdom begins in wonder. Socrates",
"If you judge, investigate. Lucius Annaeus Seneca",
"Doubt grows with knowledge. Johann Wolfgang von Goethe",
"Everything popular is wrong. Oscar Wilde",
"What you seek is seeking you. Rumi",
"Observe all men, thyself most. Benjamin Franklin",
"Doubt is the origin of wisdom. Augustine of Hippo",
"Nature does nothing uselessly. Aristotle",
"Listen to many, speak to a few. William Shakespeare",
"A closed mouth catches no flies. Miguel de Cervantes",
"Never confuse motion with action. Benjamin Franklin",
"I’m wise because I’ve been foolish.",
"Do what is right, not what is easy.",
"Silence is true wisdom’s best reply. Euripides",
"Wisdom comes only through suffering. Aeschylus",
"A loving heart is the truest wisdom. Charles Dickens",
"An overflow of good converts to bad. William Shakespeare",
"To find yourself, think for yourself. Socrates",
"My life is perfect even when it’s not. Ellen DeGeneres",
"In teaching others we teach ourselves.",
"Maturity comes with experience, not age.",
"Pain is inevitable. Suffering is optional. Haruki Murakami",
"What’s meant to be will always find a way.",
"It is better to travel well than to arrive. Buddha",
"Wisely, and slow. They stumble that run fast. William Shakespeare ",
"Love is too young to know what conscience is. William Shakespeare",
"With wisdom, comes the desire for simplicity.",
"Wise is he who collects the wisdom of others. Juan Guerra Caceras",
"Nothing has more strength than dire necessity. Euripides",
"He who would travel happily must travel light. Antoine de Saint-Exupery",
"When knowledge becomes rigid, it stops living. Anselm Kiefer",
"Wealth is the ability to fully experience life. Henry David Thoreau",
"Memory is the old, and it is afraid of the new. Osho",
"Nothing external to you has any power over you. Ralph Waldo Emerson",
"The most certain sign of wisdom is cheerfulness. Michel de Montaigne",
"Not being able to govern events, I govern myself. Michel de Montaigne",
"The mind is everything. What you think you become. Buddha",
"Happy is the hearing man; unhappy the speaking man. Ralph Waldo Emerson",
"Honesty is the first chapter in the book of wisdom. Thomas Jefferson",
"Who looks outside, dreams; who looks inside, awakes. Carl Gustav Jung",
"Most powerful is he who has himself in his own power. Lucius Annaeus Seneca",
"I don’t like that man. I must get to know him better. Abraham Lincoln",
"Complete abstinence is easier than perfect moderation. Augustine of Hippo",
"When you give yourself, you receive more than you give. Antoine de Saint-Exupery",
"If you think you know the answer, you’re far from wise. Trent Hamm",
"Judge a man by his questions rather than by his answers. Voltaire",
"We all make choices, but in the end our choices make us.",
"I am not what happened to me, I am what I choose to become. Carl Gustav Jung",
"He who knows that enough is enough will always have enough. Lao Tzu",
"He who knows, does not speak. He who speaks, does not know. Lao Tzu",
"The wisest man is generally he who thinks himself the least so. Nicolas Baileau",
"Never let the things you want make you forget the things you have.",
"Nothing ever goes away until it has taught us what we need to know.",
"As far as I’m concerned, I prefer silent vice to ostentatious virtue. Albert Einstein",
"To become a spectator of one’s own life is to escape the suffering of life. Oscar Wilde",
"Courage, dear heart. C.S. Lewis",
"He who is brave is free. Lucius Annaeus Seneca",
"From caring comes courage. Lao Tzu",
"Don’t stop until you’re proud.",
"Courage doesn’t always roar. Mary Anne Radmacher",
"What keeps me going is goals. Muhammad Ali",
"Life is tough but so you are.",
"Fortune and love favor the brave. Ovid",
"I’m strong because I’ve been weak.",
"The best way out is always through. Robert Frost",
"There is no education like adversity. Benjamin Disraeli",
"One man with courage makes a majority. Andrew Jackson",
"I’m fearless because I’ve been afraid.",
"The pain you feel now, will be a strength after some time.",
"Diligence is the mother of good fortune. Benjamin Disraeli",
"Because of a great love, one is courageous. Lao Tzu",
"Tough times never last, but tough people do.",
"Great deeds are usually wrought at great risks. Herodotus",
"He that can have patience can have what he will. Benjamin Franklin",
"Rock bottom has built more heroes than privilege.",
"I’ve never met a strong person with an easy past.",
"Things that were hard to bear are sweet to remember. Lucius Annaeus Seneca",
"Courage is like a muscle; it is strengthened by use. Ruth Gordon",
"It doesn’t matter how slow you go as long as you don’t stop. Confucius ",
"Rock bottom became the solid foundation on which I rebuilt my life. J. K. Rowling",
"The weak can never forgive. Forgiveness is the attribute of the strong. Mahatma Gandhi",
"Be faithful in small things because it is in them that your strength lies. Mother Teresa",
"Persevere and get it done. George Allen Sr",
"Never, never, never give up. Winston Churchill",
"Much effort, much prosperity. Euripides",
"Slow and steady wins the race.",
"How long should you try? Until. Jim Rohn",
"If you don’t ask, you don’t get. Stevie Wonder",
"Nothing worth having comes easy.",
"I will not walk backward in life. J. R. R. Tolkien",
"It’s pain that changes our lives. Steve Martin",
"Our whole life is solving puzzles. Erno Rubik",
"The struggle is part of the story.",
"Persevere in virtue and diligence. Plautus",
"Life is short and progress is slow. Gabriel Lippmann",
"No great thing is created suddenly. Epictetus",
"God helps those who help themselves. Benjamin Franklin",
"Patience is the companion of wisdom. Augustine of Hippo",
"Perseverance, secret of all triumphs. Victor Hugo",
"Victory belongs to the most persevering. Napoleon Bonaparte",
"I’m a slow walker, but I never walk back. Abraham Lincoln",
"In the middle of difficulty lies opportunity. Albert Einstein",
"He that can have patience can have what he will. Benjamin Franklin",
"A lost battle is a battle one thinks one has lost. Jean-Paul Sartre",
"Perseverance is a virtue that cannot be understated. Bob Riley",
"The journey of a thousand miles begins with one step. Lao Tzu",
"You may see me struggle, but you will never see me quit.",
"Perseverance is failing 19 times and succeeding the 20th. Julie Andrews",
"Thankfully, persistence is a great substitute for talent. Steve Martin",
"I was taught the way of progress is neither swift nor easy. Marie Curie",
"Persistence is to the character of man as carbon is to steel. Napoleon Hill",
"A man will fight harder for his interests than for his rights. Napoleon Bonaparte",
"Anyone who has ever made anything of importance was disciplined. Andrew Hendrixson",
"Character consists of what you do on the third and fourth tries. James A. Michener",
"Nothing is permanent in this wicked world, not even our troubles. Charlie Chaplin",
"No matter how you feel, get up, dress up, show up and never give up.",
"Don’t quit. Suffer now and live the rest of your life as a champion. Muhammad Ali",
"It’s not that I’m so smart, it’s just that I stay with problems longer. Albert Einstein ",
"The will to persevere is often the difference between failure and success. David Sarnoff",
"Ambition is the path to success. Persistence is the vehicle you arrive in. Bill Bradley",
"Perseverance is not a long race; it is many short races one after the other. Walter Elliot",
"Belief creates the actual fact. William James",
"Believing requires action. James E. Faust",
"Prayer is man’s greatest power. W. Clement Stone",
"To me faith means not worrying. John Dewey",
"Set goals. Say prayers. Work hard.",
"Faith is spiritualized imagination. Henry Ward Beecher",
"God gives where he finds empty hands. Augustine of Hippo",
"Faith is the quiet cousin of courage. Judith Hanson Lasater",
"In art as in love, instinct is enough. Anatole France",
"A man of courage is also full of faith. Marcus Tullius Cicero",
"Faith: not wanting to know what is true. Friedrich Nietzsche",
"Unless you believe, you will not understand. Augustine of Hippo",
"I believe life takes us where we need to be. Sasha Alexander",
"Live your beliefs and you can turn the world around. Henry David Thoreau",
"Prayer is to be in love, to be in love with the whole. Osho",
"Do not pray for an easier life, pray to be a stronger man. John F. Kennedy",
"Faith is not something to grasp, it is a state to grow into. Mahatma Gandhi",
"Prayer is the key of the morning and the bolt of the evening. Mahatma Gandhi",
"When someone shows you who they are, believe them the first time. Maya Angelou",
"Let life happen to you. Believe me: life is in the right, always. Rainer Maria Rilke",
"We must accept finite disappointment, but never lose infinite hope. Martin Luther King Jr.",
"Humor comes from self-confidence. Rita Mae Brown",
"We are always the same age inside. Gertrude Stein",
"Trust is the greatest intelligence. Osho",
"Confidence is one of the sexiest things. Katherine Jenkins",
"You have to laugh, especially at yourself. Madonna",
"Confidence is a stain they can’t wipe off. Lil Wayne",
"All anything takes, really, is confidence. Rachel Ward",
"Coffee in one hand. Confidence in the other.",
"Confidence comes from discipline and training. Robert Kiyosaki",
"A certain death of an artist is overconfidence. Robin Trower",
"Your energy introduces you before you even speak.",
"Act as if what you do makes a difference. It does. William James",
"Confidence is contagious. So is lack of confidence. Vince Lombardi",
"As is our confidence, so is our capacity. William Hazlitt",
"Just trust yourself, then you will know how to live. Johann Wolfgang von Goethe",
"The most beautiful thing you can wear is confidence. Blake Lively",
"Talk to yourself like you would to someone you love. Brene Brown",
"Courage is a mean with regard to fear and confidence. Aristotle",
"With confidence, you have won before you have started. Marcus Garvey",
"No one can make you feel inferior without your consent. Eleanor Roosevelt",
"Confidence cannot find a place wherein to rest in safety. Virgil",
"As soon as you trust yourself, you will know how to live. Johann Wolfgang von Goethe",
"Confidence is the most important single factor in this game. Jack Nicklaus",
"Self-confidence is the first requisite to great undertakings. Samuel Johnson ",
"All you need is ignorance and confidence and the success is sure. Mark Twain",
"Concentration comes out of a combination of confidence and hunger. Arnold Palmer",
"I’m always impressed by confidence, kindness and a sense of humor. Tamara Mellon",
"Nothing builds self-esteem and self-confidence like accomplishment. Thomas Carlyle",
"The hardest step she ever took was to blindly trust in who she was. Atticus",
"Inaction breeds doubt and fear. Action breeds confidence and courage. Dale Carnegie",
"The circulation of confidence is better than the circulation of money. James Madison",
"I have great faith in fools – self-confidence my friends will call it. Edgar Allan Poe",
"Creativity takes courage. Henri Matisse",
"Imagination rules the world. Napoleon Bonaparte",
"Zeal will do more than knowledge. William Hazlitt ",
"Pure logic is the ruin of the spirit. Antoine de Saint-Exupery",
"Without freedom, there is no creation. Jiddu Krishnamurti",
"Creativity comes from a conflict of ideas. Donatella Versace",
"The man who has no imagination has no wings. Muhammad Ali",
"Be yourself; everyone else is already taken. Oscar Wilde",
"The worst enemy to creativity is self-doubt. Sylvia Plath",
"The chief enemy of creativity is good sense. Pablo Picasso",
"I like nonsense, it wakes up the brain cells. Dr. Seuss",
"Name the greatest of all inventors. Accident. Mark Twain",
"Originality is nothing but judicious imitation. Voltaire",
"Creativity is the greatest rebellion in existence. Osho",
"Consistency is the last refuge of the unimaginative. Oscar Wilde",
"I begin with an idea, and then it becomes something else. Pablo Picasso",
"Creativity requires the courage to let go of certainties. Erich Fromm",
"Creativity – like human life itself – begins in darkness. Julia Cameron",
"In order to be irreplaceable one must always be different. Coco Chanel",
"Mystery is at the heart of creativity. That, and surprise. Julia Cameron",
"No great mind has ever existed without a touch of madness. Aristotle",
"A work of art is the unique result of a unique temperament. Oscar Wilde",
"The inner fire is the most important thing mankind possesses. Edith Södergran",
"There is no innovation and creativity without failure. Period. Brene Brown",
"To live a creative life, we must lose our fear of being wrong. Joseph Chilton Pearce",
"A man may die, nations may rise and fall, but an idea lives on. John F. Kennedy",
"The true sign of intelligence is not knowledge but imagination. Albert Einstein",
"If you want something new, you have to stop doing something old. Peter F. Drucker",
"Learn the rules like a pro, so you can break them like an artist. Pablo Picasso",
"It is better to fail in originality than to succeed in imitation. Herman Melville",
"Fashion’s not about looking back. It’s always about looking forward. Anna Wintour",
"The monotony and solitude of a quiet life stimulates the creative mind. Albert Einstein",
"When you do things from your soul, you feel a river moving in you, a joy. Rumi",
"The doer alone learneth. Friedrich Nietzsche",
"Be curious. Not judgmental. Walt Whitman",
"Sometimes you win, sometimes you learn. John Maxwell ",
"They know enough who know how to learn. Henry Adams",
"The only source of knowledge is experience. Albert Einstein",
"Any fool can know. The point is to understand. Albert Einstein",
"I never learned from a man who agreed with me. Robert A. Heinlein",
"Change is the end result of all true learning. Leo Buscaglia",
"The important thing is not to stop questioning. Albert Einstein",
"The wise learns many things from their enemies. Aristophanes",
"As long as you live, keep learning how to live. Lucius Annaeus Seneca",
"The noblest pleasure is the joy of understanding. Leonardo da Vinci",
"The most necessary learning is that which unlearns evil. Antisthenes",
"I have no special talent. I am only passionately curious. Albert Einstein",
"I am learning all the time. The tombstone will be my diploma. Eartha Kitt",
"Your most unhappy customers are your greatest source of learning. Bill Gates",
"Real learning comes about when the competitive spirit has ceased. Jiddu Krishnamurti",
"It is only when we forget all our learning that we begin to know. Henry David Thoreau",
"Education is soul crafting. Cornel West",
"Love is a better teacher than duty. Albert Einstein",
"Nine tenths of education is encouragement. Anatole France",
"Those who know how to think need no teachers. Mohandas Gandhi",
"It is a wise father that knows his own child. William Shakespeare",
"The highest result of education is tolerance. Helen Keller",
"Teaching is the highest form of understanding. Aristotle",
"A book is a dream that you hold in your hands. Neil Gaiman",
"People only see what they are prepared to see. Ralph Waldo Emerson",
"Nothing ever becomes real till it is experienced. John Keats",
"A student of life considers the world a classroom. Harvey Mackay",
"An investment in knowledge pays the best interest. Benjamin Franklin",
"Don’t let schooling interfere with your education. Mark Twain",
"Children have more need of models than of critics. Carolyn Coats",
"Education is the ability to meet life’s situations. Dr. John G. Hibben",
"If you think education is expensive, try ignorance. Andy McIntyre",
"The great aim of education is not knowledge but action. Herbert Spencer ",
"A child educated only at school is an uneducated child. George Santayana",
"Be brave. Take risks. Nothing can substitute experience. Paulo Coelho",
"Experience, travel. These are an education in themselves. Euripides",
"The roots of education are bitter, but the fruit is sweet. Aristotle",
"There is no greater education than one that is self-driven. Neil deGrasse Tyson",
"The mind unlearns with difficulty what it has long learned. Lucius Annaeus Seneca",
"Education is not filling a pail but the lighting of a fire. William Butler Yeats",
"I cannot teach anybody anything, I can only make them think. Socrates",
"In this life, all you need is for someone to believe in you. J. R. Martinez",
"Intelligence plus character – that is the goal of true education. Martin Luther King Jr.",
"If you want happiness for a lifetime, help the next generation. Chinese saying",
"The mind is not a vessel to be filled, but a fire to be kindled. Plutarch",
"Education is not preparation for life; education is life itself. John Dewey",
"Educate the children and it won’t be necessary to punish the men. Pythagoras",
"The world is a book and those who do not travel read only one page. Augustine of Hippo",
"It’s not that hard to stay grounded. It’s the way I was brought up. Sidney Crosby",
"Educating the mind without educating the heart is no education at all. Aristotle",
"Work without love is slavery. Mother Teresa",
"You have to fight to reach your dream. Lionel Messi",
"Do your duty today and repent tomorrow. Mark Twain",
"What is once well done is done forever. Henry David Thoreau",
"Don’t mistake activity with achievement. John Wooden",
"All happiness depends on courage and work. Honore de Balzac",
"You are not your resume, you are your work. Seth Godin",
"Without hard work, nothing grows but weeds. Gordon B. Hinckley",
"Let the beauty of what you love be what you do. Rumi",
"Pleasure in the job puts perfection in the work. Aristotle",
"I learned the value of hard work by working hard. Margaret Mead",
"Work hard, be kind, and amazing things will happen. Conan O’Brien ",
"As a cure for worrying, work is better than whiskey. Ralph Waldo Emerson",
"The beginning is the most important part of the work. Plato",
"The reward of one duty is the power to fulfill another. George Eliot",
"Once you do something you love, you never have to work again. Willie Hill",
"Leadership is influence. John C. Maxwell",
"One must steer, not talk. Lucius Annaeus Seneca",
"A leader is a dealer in hope. Napoleon Bonaparte",
"To lead people walk behind them. Lao Tzu",
"A good example is the best sermon. Benjamin Franklin",
"Anyone can hold the helm when the sea is calm. Publilius Syrus",
"The speed of the leader is the speed of the gang. Mary Kay Ash",
"A ruler should be slow to punish and swift to reward. Ovid",
"He who is not a good servant will not be a good master. Plato",
"Each person must live their life as a model for others. Rosa Parks",
"Leaders don’t create followers, they create more leaders. Tom Peters",
"The strength of the group is the strength of the leaders. Vince Lombardi",
"You don’t have to hold a position in order to be a leader. Henry Ford",
"Build your reputation by helping other people build theirs. Anthony J. D’Angelo",
"Leadership is the capacity to translate vision into reality. Warren Bennis",
"When you can’t make them see the light, make them feel the heat. Ronald Reagan ",
"Keep your fears to yourself, but share your courage with others. Robert Louis Stevenson",
"To handle yourself, use your head; to handle others, use your heart. Eleanor Roosevelt",
"To be a leader, bring certainty, to an environment where there isn’t any. Tony Robbins",
"Attitude is everything. Charles Swindoll",
"Be groovy or leave, man. Bob Dylan",
"A true man hates no one. Napoleon Bonaparte",
"What you are comes to you. Ralph Waldo Emerson",
"Who sows virtue reaps honor. Leonardo da Vinci",
"Don’t find fault, find a remedy. Henry Ford",
"A great mind becomes a great fortune. Lucius Annaeus Seneca",
"Humor is mankind’s greatest blessing. Mark Twain",
"The greatest remedy for anger is delay. Lucius Annaeus Seneca",
"Love all, trust a few, do wrong to none. William Shakespeare",
"Showing off is the fool’s idea of glory. Bruce Lee",
"Let’s not be narrow, nasty, and negative. T. S. Eliot",
"Be someone who you would want to be around. Craig Jarrow",
"Energy and persistence conquer all things. Benjamin Franklin",
"A great man is always willing to be little. Ralph Waldo Emerson",
"Ethics is nothing else than reverence for life. Albert Schweitzer",
"Humility is the solid foundation of all virtues. Confucius",
"Goodness is the only investment that never fails. Henry David Thoreau",
"Be true to your work, your word, and your friend. Henry David Thoreau",
"A quick temper will make a fool of you soon enough. Bruce Lee",
"Nothing great was ever achieved without enthusiasm. Ralph Waldo Emerson",
"Knowledge will give you power, but character respect. Bruce Lee",
"Strive not to be a success, but rather to be of value. Albert Einstein",
"Swallow your pride, you will not die, it’s not poison. Bob Dylan",
"Attitude is a little thing that makes a big difference. Winston Churchill",
"Remind yourself that your task is to be a good human being. Marcus Aurelius",
"Be careless in your dress if you will, but keep a tidy soul. Mark Twain",
"Let us train our minds to desire what the situation demands. Lucius Annaeus Seneca",
"Really great people make you feel that you, too, can become great. Mark Twain",
"Waste no more time arguing about what a good man should be. Be one. Marcus Aurelius",
"Being both soft and strong is a combination very few have mastered.",
"The firm, the enduring, the simple, and the modest are near to virtue. Confucius",
"Life is good when we think it’s good. Life is bad when we don’t think. Douglas Horton",
"To hold a pen is to be at war. Voltaire",
"Easy reading is damn hard writing. Nathaniel Hawthorne",
"Write what should not be forgotten. Isabel Allende",
"The first draft of anything is shit. Ernest Hemingway",
"An author, behind his words, is naked. Terri Guillemets",
"Tears are words that need to be written. Paulo Coelho",
"If it sounds like writing, I rewrite it. Elmore Leonard",
"Every writer I know has trouble writing. Joseph Heller",
"The wastebasket is a writer’s best friend. Isaac Bashevis Singer",
"A word after a word after a word is power. Margaret Atwood",
"If I don’t write to empty my mind, I go mad. Lord Byron",
"The best style is the style you don’t notice. Somerset Maugham",
"Fill your paper with the breathings of your heart. William Wordsworth",
"The scariest moment is always just before you start. Stephen King",
"A professional writer is an amateur who didn’t quit. Richard Bach",
"You must stay drunk on writing so reality cannot destroy you. Ray Bradbury",
"One day I will find the right words, and they will be simple. Jack Kerouac ",
"We write to taste life twice, in the moment and in retrospect. Anaïs Nin",
"The art of writing is the art of discovering what you believe. Gustave Flaubert",
"There is no greater agony than bearing an untold story inside you. Maya Angelou",
"There is no real ending. It’s just the place where you stop the story. Frank Herbert",
"Writing is an exploration. You start from nothing and learn as you go. E. L. Doctorow",
"The purpose of a writer is to keep civilization from destroying itself. Albert Camus",
"The most beautiful things are those that madness prompts and reason writes. André Gide",
"Change before you have to. Jack Welch",
"To say goodbye is to die a little. Raymond Chandler",
"There is nothing so stable as change. Bob Dylan",
"It is in changing that we find purpose. Heraclitus",
"Every day is a chance to change your life.",
"In a gentle way, you can shake the world. Mahatma Gandhi",
"Our only security is our ability to change. John Lilly",
"Change your thoughts and you change your world. Norman Vincent Peale",
"Intelligence is the ability to adapt to change. Stephen Hawking",
"No map is possible because life goes on changing. Osho",
"If it doesn’t challenge you, it won’t change you.",
"It is never too late to be what you might have been. George Eliot",
"Change is not merely necessary to life – it is life. Alvin Toffler",
"If you want to make enemies, try to change something. Woodrow Wilson",
"Failure is not fatal, but failure to change might be. John Wooden",
"You affect your subconscious mind by verbal repetition. W. Clement Stone",
"When you blame others, you give up your power to change. Robert Anthony",
"It is not necessary to change. Survival is not mandatory. W. Edwards Deming ",
"Prayer does not change God, but it changes him who prays. Soren Kierkegaard",
"To improve is to change; to be perfect is to change often. Winston Churchill",
"To change one’s life: Start immediately. Do it flamboyantly. William James",
"Only the new, accepted deeply and totally, can transform you. Osho",
"No matter what people tell you, words and ideas can change the world. Robin Williams",
"Let your smile change the world, but don’t let the world change your smile.",
"Much effort, much prosperity. Euripides",
"Make your life a masterpiece. Brian Tracy",
"Success is the child of audacity. Benjamin Disraeli",
"The best revenge is massive success. Franck Sinatra",
"A goal without a plan is just a wish. Antoine de Saint-Exupery",
"We aim above the mark to hit the mark. Ralph Waldo Emerson",
"I never dream of success. I worked for it. Estee Lauder",
"The harder the battle the sweeter the victory. Bob Marley",
"Action is the foundational key to all success. Pablo Picasso",
"The secret of success is constancy of purpose. Benjamin Disraeli",
"What you think today is what you live tomorrow. Remez Sasson",
"Success is where preparation and opportunity meet. Bobby Unser",
"Be content to act, and leave the talking to others. Baltasar",
"Success is how high you bounce when you hit bottom. George S. Patton",
"No one knows what to say in the loser’s locker room. Muhammad Ali",
"If you have no critics you’ll likely have no success. Malcolm X",
"Everybody pities the weak; jealousy you have to earn. Arnold Schwarzenegger",
"The measure of success is happiness and peace of mind. Bobby Davro",
"I couldn’t wait for success, so I went ahead without it. Jonathan Winters",
"Start where you are. Use what you have. Do what you can. Arthur Ashe",
"Before anything else, preparation is the key to success. Alexander Graham Bell",
"Success is the accumulation of small advantages over time.Aaron Lynn",
"The path to success is to take massive, determined action. Tony Robbins",
"The secret of my success is a two word answer: Know people. Harvey S. Firestone",
"Don’t let what you cannot do interfere with what you can do. John R. Wooden",
"I find that the harder I work, the more luck I seem to have. Thomas Jefferson ",
"It’s not whether you get knocked down, it’s whether you get up. Vince Lombardi",
"Judge your success by what you had to give up in order to get it. Dalai Lama",
"The successful warrior is the average man, with laser-like focus. Bruce Lee",
"I attribute my success to this – I never gave or took any excuse. Florence Nightingale",
"My success isn’t a result of arrogance – it’s a result of belief. Conor McGregor",
"Success is the sum of small efforts, repeated day in and day out. Robert Collier",
"I always wanted to be the best and to get the most out of myself. Sidney Crosby",
"Success is only meaningful and enjoyable if it feels like your own. Michelle Obama",
"Success is largely a matter of holding on after others have let go. William Feather",
"I want to be the best, so whatever comes with that, I’ll have to accept. Sidney Crosby",
"Success is nothing more than a few simple disciplines, practiced every day. Jim Rohn",
"Fear and time are inseparable. Jiddu Krishnamurti",
"Fear is stupid. So are regrets. Marilyn Monroe",
"Where fear is, happiness is not. Lucius Annaeus Seneca",
"Always do what you are afraid to do. Ralph Waldo Emerson",
"Fear makes the wolf bigger than he is. German proverb",
"Fear is destructive; love is a creative energy. Osho",
"If it scares you, it might be a good thing to try. Seth Godin",
"Limits, like fear, is often an illusion. Michael Jordan",
"Fear tricks us into living a boring life. Donald Miller",
"To conquer fear is the beginning of wisdom. Bertrand Russell",
"People living deeply have no fear of death. Anaïs Nin",
"The only thing we have to fear is fear itself. Franklin D. Roosevelt",
"Thinking will not overcome fear but action will. W. Clement Stone",
"Curiosity will conquer fear even more than bravery will. James Stephens",
"The constant assertion of belief is an indication of fear. Jiddu Krishnamurti",
"Everything you’ve ever wanted is on the other side of fear. George Addair",
"Nothing in life is to be feared. It is only to be understood. Marie Curie",
"The mind that is always after explanations is an afraid mind. Osho",
"Sometimes the fear won’t go away, so you’ll have to do it afraid.",
"Courage is resistance to fear, mastery of fear, not absence of fear. Mark Twain",
"Fear has two meanings – Forget Everything And Run or Face Everything And Rise.",
"Don’t worry, be happy. Bobby McFerrin",
"Worry less, smile more.",
"Pray, and let God worry. Martin Luther",
"What worries you, masters you. John Locke",
"Anxiety is the dizziness of freedom. Soren Kierkegaard",
"It’s ok to worry – it means you care.",
"The sovereign cure for worry is prayer. William James",
"Worry often gives a small thing a big shadow. Swedish proverb",
"Most things I worry about never happen anyway. Tom Petty",
"You can destroy your now by worrying about tomorrow. Janis Joplin",
"I never worry about action, but only about inaction. Winston Churchill",
"As a cure for worrying, work is better than whiskey. Thomas A. Edison",
"A day of worry is more exhausting than a day of work. John Lubbock",
"The mind that is anxious about the future is miserable. Lucius Annaeus Seneca",
"I try not to worry about things I can’t do anything about. Christopher Walken",
"Worry is a useless mulling over of things we cannot change. Peace Pilgrim",
"We want predictability, even though it’s impossible to get. Henri Junttila",
"The problem is that worrying doesn’t actually solve anything.Celestine Chua",
"Let our advance worrying become advance thinking and planning. Winston Churchill",
"Throw off your worries when you throw off your clothes at night. Napoleon Bonaparte",
"Worry never robs tomorrow of its sorrow, it only saps today of its joy. Leo Buscaglia",
"Stumbling is not falling. Malcolm X",
"Turn your wounds into wisdom. Oprah Winfrey",
"Better an ‘oops’ than a ‘what if’.",
"Failure’s a natural part of life. John Malkovich",
"Giving up is the greatest failure. Jack Ma",
"Not failure, but low aim, is crime. James Russell Lowell",
"Mistakes are the portals of discovery. James Joyce",
"My reputation grows with every failure. George Bernard Shaw",
"Failure is success if we learn from it. Malcolm Forbes",
"Reward worthy failure – experimentation. Bill Gates",
"Failure is a detour, not a dead-end street. Zig Ziglar",
"Experience is the name we give to our mistakes. Oscar Wilde",
"Remember that failure is an event, not a person. Zig Ziglar",
"There are no mistakes or failures, only lessons. Denis Waitley",
"Fear of failure has always been my best motivator. Douglas Wood",
"You have to be able to accept failure to get better. LeBron James",
"Failure is not fatal, but failure to change might be. John Wooden",
"There are some defeats more triumphant than victories. Michel de Montaigne",
"Failure is the condiment that gives success its flavor. Truman Capote",
"Success is not a good teacher, failure makes you humble. Shahrukh Khan",
"The sooner you fail, the less afraid you are to fail again.Brendan Baker",
"Error is just as important a condition of life as truth. Carl Gustav Jung",
"Once you can accept failure, you can have fun and success. Rickey Henderson",
"Testing leads to failure, and failure leads to understanding. Burt Rutan",
"Ambitious failure, magnificent failure, is a very good thing. Guy Kawasaki",
"Do not fear mistakes. You will know failure. Continue to reach out. Benjamin Franklin",
"Life is a succession of lessons which must be lived to be understood. Helen Keller ",
"Regrets belong to the past. Marlon Brando",
"Life’s too short for regrets. Nicholas Hoult",
"Remorse is the poison of life. Charlotte Bronte",
"My head has got regrets, but I haven’t. Frank Bruno",
"There are no regrets in life, just lessons. Jennifer Aniston",
"Regret for wasted time is more wasted time. Mason Cooley",
"Fear is only temporary. Regrets last forever.",
"Regrets are ridiculous, so I don’t regret, no. Nicole Kidman",
"Regrets are the natural property of grey hairs. Charles Dickens",
"I have often regretted my speech, never my silence. Publilius Syrus",
"Never look back unless you are planning to go that way. Henry David Thoreau",
"A man is not old until regrets take the place of dreams. John Barrymore",
"Never make permanent decisions based on temporary feelings.",
"Before it’s too late, tell them everything you’ve ever wanted to say.",
"Never regret anything because one time it was exactly what you wanted.",
"I don’t regret a thing I’ve done. I only regret the things I didn’t do. Ingrid Bergman",
"Be so good they can’t ignore you. Steve Martin",
"The haters always scream the loudest. Tucker Max",
"I don’t have to be what you want me to be. Muhammad Ali",
"To refrain from imitation is the best revenge. Marcus Aurelius",
"Have you ever met a hater doing better than you?",
"I destroy my enemies when I make them my friends. Abraham Lincoln",
"Haters keep on hating, cause somebody’s gotta do it. Chris Brown",
"Always forgive your enemies. Nothing annoys them so much. Oscar Wilde ",
"Your love makes me strong, your hate makes me unstoppable. Cristiano Ronaldo",
"You pick up some fans and a handful of haters along the way. Bruno Mars",
"The best revenge is to be unlike him who performed the injury. Marcus Aurelius",
"Doubts are death. Maharishi Mahesh Yogi",
"Inactivity is death. Benito Mussolini",
"Security is a kind of death. Tennessee Williams",
"My life, my death, my choice. Terry Pratchett",
"Death is a debt we all must pay. Euripides",
"Death is the final wake-up call. Douglas Horton",
"Death, only, renders hope futile. Edgar Rice Burroughs",
"Every man dies. Not every man lives. William Wallace",
"Death is the beginning of something. Edith Piaf",
"Our business is with life, not death. George Wald",
"I don’t want to die without any scars. Chuck Palahniuk",
"Death is a distant rumor to the young. Andrew A. Rooney",
"Death is just life’s next big adventure. J. K. Rowling",
"He who doesn’t fear death dies only once. Giovanni Falcone",
"Grief does not change you, it reveals you. John Green",
"Death is frightening, and so is Eternal Life. Mason Cooley",
"The idea is to die young as late as possible. Ashley Montagu",
"I would rather die of passion than of boredom. Vincent van Gogh",
"I feel monotony and death to be almost the same. Charlotte Bronte",
"If by my life or death I can protect you, I will. J. R. R. Tolkien",
"Guilt is perhaps the most painful companion of death. Coco Chanel",
"A man who won’t die for something is not fit to live. Martin Luther King Jr.",
"A man who lives fully is prepared to die at any time. Mark Twain",
"Do not fear death so much but rather the inadequate life. Bertolt Brecht",
"A thing is not necessarily true because a man dies for it. Oscar Wilde",
"I have no fear of death. More important, I don’t fear life. Steven Seagal",
"Our dead are never dead to us, until we have forgotten them. George Eliot",
"My fear was not of death itself, but a death without meaning. Huey Newton",
"Don’t take life too seriously. You’ll never get out of it alive. Elbert Hubbard ",
"Death is the only pure, beautiful conclusion of a great passion. D. H. Lawrence",
"Take care of your life and the Lord will take care of your death. George Whitefield",
"To the well-organized mind, death is but the next great adventure. J.K. Rowling",
"If life must not be taken too seriously, then so neither must death. Samuel Butler",
"It is not death or pain that is to be dreaded, but the fear of pain or death. Epictetus",
"You get knocked down, you get up, brush yourself off, and you get back to work. Barack Obama",
"I’d rather be a failure at something I love than a success at something I hate. George Burns",
"The only failure one should fear, is not hugging to the purpose they see as best. George Eliot",
"Whenever you are confronted with an opponent. Conquer him with love. Mohandas Gandhi",
"A hater is nothing but a fan. They just don’t know how to express it in positive way. Bar Refaeli",
"It is the unknown we fear when we look upon death and darkness, nothing more. J.K. Rowling",
"The season of failure is the best time for sowing the seeds of success. Paramahansa Yogananda",
"The world hates change, yet it is the only thing that has brought progress. Charles Kettering",
"For every minute you are angry you lose sixty seconds of happiness. -Ralph Waldo Emerson",
"Happiness is not a station you arrive at, but a manner of traveling. -Margaret Lee Runbeck",
"True happiness arises, in the first place, from the enjoyment of one’s self. -Joseph Addison",
"Base your happiness on taking action toward those goals, not on attaining them. –Laura J. Tong",
"Happiness resides not in possessions, and not in gold, happiness dwells in the soul. -Democritus",
"True friendship comes when the silence between two people is comfortable. -David Tyson",
"Gratitude is not only the greatest of virtues, but the parent of all others. -Marcus Tullius Cicero",
"Wherever there is a human being, there is an opportunity for a kindness. -Lucius Annaeus Seneca",
"The best way to find yourself is to lose yourself in the service of others. -Mohandas Gandhi",
"Life is really a dance if you are original, and you are meant to be original. –Osho",
"Most people have never learned that one of the main aims in life is to enjoy it. -Samuel Butler",
"The unexamined life is not worth living. -Socrates",
"Life is like riding a bicycle. To keep your balance, you must keep moving. -Albert    Einstein",
"Life really does begin at forty. Up until then, you are just doing research.- Carl Gustav Jung",
"In three words I can sum up everything I’ve learned about life: it goes on. -Robert Frost",
"Life can only be understood backwards; but it must be lived forwards. -Soren Kierkegaard",
"Love needs great courage. It needs great courage because it needs the sacrifice of the ego. Osho",
"A lifetime of happiness! No man alive could bear it: it would be hell on earth. -George Bernard",
"He who controls others may be powerful, but he who has mastered himself is mightier still. -Lao Tzu",
"You can’t put a limit on anything. The more you dream, the farther you get. -Michael Phelps",
"You are imperfect, permanently and inevitably flawed. And you are beautiful.- Amy Bloom",
"Forgiveness does not change the past, but it does enlarge the future. -Paul Boese",
"We must learn to live together as brothers or perish together as fools. -Martin Luther King Jr ",
"Peace cannot be kept by force; it can only be achieved by understanding. -Albert Einstein",
"When the power of love overcomes the love of power the world will know peace. -Jimi Hendrix",
"The ability to observe without evaluating is the highest form of intelligence. -Jiddu Krishnamurti",
"I was living the American dream and I realized it wasn’t my dream. –Joshua Fields Millburn",
"Instead of working so hard to make ends meet, work on having fewer ends. –Courtney Carver",
"A fool thinks himself to be wise, but a wise man knows himself to be a fool. William Shakespeare",
"People cry, not because they’re weak. It’s because they’ve been strong for too long. Johnny Depp",
"Too many people overvalue what they are not and undervalue what they are. Malcolm S. Forbes",
"Confidence in the goodness of another is good proof of one’s own goodness. Michel de",
"Never bend your head. Always hold it high. Look the world straight in the face. Helen Keller",
"My confidence comes from the daily grind – training my butt off day in and day out. Hope Solo",
"I never made one of my discoveries through the process of rational thinking. Albert Einstein",
"Creativity is allowing yourself to make mistakes. Art is knowing which ones to keep. Scott",
"Example is not the main thing in influencing others. It is the only thing. Albert Schweitzer",
"A genuine leader is not a searcher for consensus but a molder of consensus. Martin Luther King",
"May you live your life as if the maxim of your actions were to become universal law. Immanuel",
"Drop all your scientific attitudes. Become a little more fluid, more melting, more merging. Osho",
"“All our dreams can come true if we have the courage to pursue them.”- Walt Disney",
"“It does not matter how slowly you go, so long as you do not stop.”- Confucius",
" “Success is walking from failure to failure with no loss of enthusiasm.”- Winston Churchill",
"“Don’t cry because it’s over, smile because it happened.” — Dr. Seuss",
"“You only live once, but if you do it right, once is enough.” — Mae West",
" “Opportunities don’t happen. You create them.” — Chris Grosser",
" “Once you choose hope, anything’s possible.” — Christopher Reeve",
"“The best revenge is massive success.” — Frank Sinatra",
" “The difference between winning and losing is most often not quitting.”- Walt Disney",
" “I have not failed. I’ve just found 10,000 ways that won’t work.” — Thomas Edison",
" “When you cease to dream you cease to live.” — Malcolm Forbes",
"“May you live every day of your life.” — Jonathan Swift",
" “No one can make you feel inferior without your consent.” — Eleanor Roosevelt",
" “Failure is another steppingstone to greatness.” — Oprah Winfrey",
"“If you’re going through hell, keep going.” — Winston Churchill",
"“In order to be irreplaceable one must always be different.” — Coco Chanel",
" “What seems to us as bitter trials are often blessings in disguise.” — Oscar Wilde",
" “You miss 100 percent of the shots you don’t take.” — Wayne Gretzky",
"“The longer I live, the more beautiful life becomes.” — Frank Lloyd Wright",
"“You must expect great things of yourself before you can do them.”- Michael Jordan",
" “If you can’t explain it simply, you don’t understand it well enough.”- Albert Einstein",
"“Keep your face to the sunshine and you can never see the shadow.”- Helen Keller",
"“The successful warrior is the average man, with laser-like focus.” — Bruce Lee",
"“If you always do what interests you, at least one person is pleased.”- Katharine Hepburn",
"“I avoid looking forward or backward, and try to keep looking upward.”- Charlotte Bronte",
"“Life is short, and it is here to be lived.” — Kate Winslet",
" “Everything you can imagine is real.” — Pablo Picasso",
" Leadership is the capacity to translate vision into reality. —Warren Bennis",
"Lead me, follow me, or get out of my way. — General George Patton",
"A leader is a dealer in hope. —Napoleon BonaparteYou don’t need a title to be a leader. –Multiple Attributions",
"A leader is one who knows the way, goes the way, and shows the way. —John Maxwell",
"To command is to serve, nothing more and nothing less. —Andre Malraux",
"He who has never learned to obey cannot be a good commander. —Aristotle",
"Anyone can hold the helm when the sea is calm. —Publilius Syrus",
"Leadership is influence. —John C. Maxwell",
"The key to successful leadership today is influence, not authority. —Kenneth Blanchard",
"What you see is not what you think – Ralph Jones"]
